# Dockerfile for Kafka
FROM confluentinc/cp-kafka:latest

# Exponera porten
EXPOSE 9092

ENV CLUSTER_ID=W5CaV_08RiaRypEHwYPchA \
    KAFKA_NODE_ID=1 \
    KAFKA_PROCESS_ROLES=broker,controller \
    KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093 \
    KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092 \
    KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER \
    KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka:9093 \
    KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT \
    KAFKA_LOG_DIRS=/var/lib/kafka/data \
    KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1 \
    KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1 \
    KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1 \
    KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka.app.cloud.cbh.kth.se:9092

# Starta Kafka
CMD ["kafka-server-start", "/etc/kafka/server.properties"]
