apiVersion: v1
kind: Service
metadata:
  name: kafka
spec:
  type: ClusterIP
  selector:
    app: kafka
  ports:
    - name: plaintext
      port: 9092
      targetPort: plaintext
    - name: controller
      port: 9093
      targetPort: controller